namespace NHT_Marine_BE.Utilities
{
    public static class SuccessMessage
    {
        // Authentication related
        public const string SIGN_IN_SUCCESSFULLY = "SIGN_IN_SUCCESSFULLY";
        public const string SIGN_UP_SUCCESSFULLY = "SIGN_UP_SUCCESSFULLY";
        public const string REFRESH_TOKEN_SUCCESSFULLY = "REFRESH_TOKEN_SUCCESSFULLY";
        public const string DEACTIVATE_ACCOUNT_SUCCESSFULLY = "DEACTIVATE_ACCOUNT_SUCCESSFULLY";
        public const string RESET_PASSWORD_EMAIL_SENT = "RESET_PASSWORD_EMAIL_SENT";
        public const string RESET_PASSWORD_SUCCESSFULLY = "RESET_PASSWORD_SUCCESSFULLY";
        public const string GOOGLE_AUTH_SUCCESSFULLY = "GOOGLE_AUTH_SUCCESSFULLY";
        public const string VERIFY_PERMISSION_SUCCESSFULLY = "VERIFY_PERMISSION_SUCCESSFULLY";

        // Users related
        public const string CHANGE_PASSWORD_SUCCESSFULLY = "CHANGE_PASSWORD_SUCCESSFULLY";
        public const string UPDATE_USER_SUCCESSFULLY = "UPDATE_USER_SUCCESSFULLY";
        public const string CREATE_STAFF_SUCCESSFULLY = "CREATE_STAFF_SUCCESSFULLY";
        public const string CREATE_ROLE_SUCCESSFULLY = "CREATE_ROLE_SUCCESSFULLY";
        public const string UPDATE_ROLE_SUCCESSFULLY = "UPDATE_ROLE_SUCCESSFULLY";
        public const string DELETE_ROLE_SUCCESSFULLY = "DELETE_ROLE_SUCCESSFULLY";
        public const string DEACTIVATE_CUSTOMER_SUCCESSFULLY = "DEACTIVATE_CUSTOMER_SUCCESSFULLY";

        // Services related
        public const string UPLOAD_IMAGE_SUCCESSFULLY = "UPLOAD_IMAGE_SUCCESSFULLY";
        public const string DELETE_IMAGE_SUCCESSFULLY = "DELETE_IMAGE_SUCCESSFULLY";

        // Categories related
        public const string CREATE_CATEGORY_SUCCESSFULLY = "CREATE_CATEGORY_SUCCESSFULLY";
        public const string UPDATE_CATEGORY_SUCCESSFULLY = "UPDATE_CATEGORY_SUCCESSFULLY";
        public const string DELETE_CATEGORY_SUCCESSFULLY = "DELETE_CATEGORY_SUCCESSFULLY";

        // Products related
        public const string CREATE_PRODUCT_SUCCESSFULLY = "CREATE_PRODUCT_SUCCESSFULLY";
        public const string UPDATE_PRODUCT_SUCCESSFULLY = "UPDATE_PRODUCT_SUCCESSFULLY";
        public const string DELETE_PRODUCT_SUCCESSFULLY = "DELETE_PRODUCT_SUCCESSFULLY";

        // Orders and carts related
        public const string ADD_TO_CART_SUCCESSFULLY = "ADD_TO_CART_SUCCESSFULLY";
        public const string UPDATE_CART_SUCCESSFULLY = "UPDATE_CART_SUCCESSFULLY";
        public const string RESET_CART_SUCCESSFULLY = "RESET_CART_SUCCESSFULLY";
        public const string PLACE_ORDER_SUCCESSFULLY = "PLACE_ORDER_SUCCESSFULLY";
        public const string UPDATE_ORDER_SUCCESSFULLY = "UPDATE_ORDER_SUCCESSFULLY";

        // Promotion and coupon related
        public const string CREATE_PROMOTION_SUCCESSFULLY = "CREATE_PROMOTION_SUCCESSFULLY";
        public const string UPDATE_PROMOTION_SUCCESSFULLY = "UPDATE_PROMOTION_SUCCESSFULLY";
        public const string DISABLE_PROMOTION_SUCCESSFULLY = "DISABLE_PROMOTION_SUCCESSFULLY";
        public const string CREATE_COUPON_SUCCESSFULLY = "CREATE_COUPON_SUCCESSFULLY";
        public const string UPDATE_COUPON_SUCCESSFULLY = "UPDATE_COUPON_SUCCESSFULLY";
        public const string DISABLE_COUPON_SUCCESSFULLY = "DISABLE_COUPON_SUCCESSFULLY";

        // Stock related
        public const string CREATE_DAMAGE_TYPE_SUCCESSFULLY = "CREATE_DAMAGE_TYPE_SUCCESSFULLY";
        public const string UPDATE_DAMAGE_TYPE_SUCCESSFULLY = "UPDATE_DAMAGE_TYPE_SUCCESSFULLY";
        public const string DELETE_DAMAGE_TYPE_SUCCESSFULLY = "DELETE_DAMAGE_TYPE_SUCCESSFULLY";
        public const string CREATE_STORAGE_TYPE_SUCCESSFULLY = "CREATE_STORAGE_TYPE_SUCCESSFULLY";
        public const string UPDATE_STORAGE_TYPE_SUCCESSFULLY = "UPDATE_STORAGE_TYPE_SUCCESSFULLY";
        public const string DELETE_STORAGE_TYPE_SUCCESSFULLY = "DELETE_STORAGE_TYPE_SUCCESSFULLY";
        public const string CREATE_SUPPLIER_SUCCESSFULLY = "CREATE_SUPPLIER_SUCCESSFULLY";
        public const string UPDATE_SUPPLIER_SUCCESSFULLY = "UPDATE_SUPPLIER_SUCCESSFULLY";
        public const string DELETE_SUPPLIER_SUCCESSFULLY = "DELETE_SUPPLIER_SUCCESSFULLY";
        public const string UPDATE_INVENTORY_SUCCESSFULLY = "UPDATE_INVENTORY_SUCCESSFULLY";
        public const string CREATE_STORAGE_SUCCESSFULLY = "CREATE_STORAGE_SUCCESSFULLY";
        public const string UPDATE_STORAGE_SUCCESSFULLY = "UPDATE_STORAGE_SUCCESSFULLY";
        public const string DELETE_STORAGE_SUCCESSFULLY = "DELETE_STORAGE_SUCCESSFULLY";
        public const string TRACK_IMPORT_SUCCESSFULLY = "TRACK_IMPORT_SUCCESSFULLY";
        public const string DISTRIBUTE_IMPORT_SUCCESSFULLY = "DISTRIBUTE_IMPORT_SUCCESSFULLY";

        // Transactions related
        public const string CREATE_DELIVERY_SERVICE_SUCCESSFULLY = "CREATE_DELIVERY_SERVICE_SUCCESSFULLY";
        public const string UPDATE_DELIVERY_SERVICE_SUCCESSFULLY = "UPDATE_DELIVERY_SERVICE_SUCCESSFULLY";
        public const string DELETE_DELIVERY_SERVICE_SUCCESSFULLY = "DELETE_DELIVERY_SERVICE_SUCCESSFULLY";
        public const string CREATE_ORDER_STATUS_SUCCESSFULLY = "CREATE_ORDER_STATUS_SUCCESSFULLY";
        public const string UPDATE_ORDER_STATUS_SUCCESSFULLY = "UPDATE_ORDER_STATUS_SUCCESSFULLY";
        public const string DELETE_ORDER_STATUS_SUCCESSFULLY = "DELETE_ORDER_STATUS_SUCCESSFULLY";
    }
}
